#!/usr/bin/env bash
#iam here

subdomains=( "www" "lb-01" "web-01" "web-02" )

look_up ()

{
   local domain="$1"
   local subdomain="$2"
   local dest=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $5}')
   local type=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2 {print $4}')
   echo "The subdomain $subdomain is a $type record and points to $dest"
}

if [[ $# -lt  2 ]]; then
        for i in "${subdomains[@]}";
        do
                look_up "$1" "$i"
        done
else
        look_up "$@"
fi
