#!/usr/bin/env bash
#making a redirection
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
match="server {"
redirection="\
	location /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4}"
sudo sed -i "/$match/a\
	$redirection" /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx start
