#!/usr/bin/env bash
#installing HAproxy
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.9 -y
sudo apt-get install haproxy=2.9.\* -y
config=\
"
frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 355975-web-01 54.165.2.91:80 check
    server 355975-web-02 54.210.108.204:80 check
"

sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

sudo bash -c "sudo echo -e '$config' > /etc/haproxy/haproxy.cfg"

sudo chown -R "$USER":"$USER" /etc/default

sudo echo "ENABLED=1" >> /etc/default/haproxy

if [[ "$(pgrep -c haproxy)" -le 0 ]]; then
  sudo service haproxy start
else
  sudo service haproxy restart
fi

