#!/usr/bin/env bash
#installing HAproxy
sudo apt-get update
sudo add-apt-repository ppa:vbernat/haproxy-2.9 -y
sudo apt-get install haproxy=2.9.\* -y
config=\
"global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 355975-web-01 54.165.2.91:80 check
    server 355975-web-02 54.210.108.204:80 check"

sudo bash -c "sudo echo -e '$config' > /etc/haproxy/haproxy.cfg"

sudo chown -R "$USER":"$USER" /etc/default

sudo echo "ENABLED=1" >> /etc/default/haproxy

if [[ "$(pgrep -c haproxy)" -le 0 ]]; then
  sudo service haproxy start
else
  sudo service haproxy restart
fi

