#!/bin/bash
# Set IFS to colon to split fields in /etc/passwd

IFS=":"

while read -r username password uid gid user_info home shell; do
    echo "The user $username is part of the $gid gang,"
    echo "lives in $home and rides $shell."
    echo "USER ID's place is protected by the passcode $password,"
    echo "more info about the user here: $user_info"
    echo
done < /etc/passwd
