#!/usr/bin/env bash
#iam here
sudo service nginx stop
sudo chown -R nginx:nginx /etc/nginx /var/log/nginx
sudo chmod 755 /etc/nginx/nginx.conf
sudo sed -i 's/^user www-data.*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server;/listen *:8080;/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen [::]:8080;/' /etc/nginx/sites-enabled/default
sudo kill 21
sudo nginx -s reload
sudo -u nginx bash -c 'service nginx restart'
